### ISSUE TITLE
Initial population is not diverse enough

### ISSUE THREAD

**Issue by DewaldDeJager** [ErnstEksteen/COS301_GA-SATSolver#57]
The initial randomly generated population does not seem random enough. Given how fast that currently is and that it is a once off process, perhaps we can add a manual diversification mechanism.

We could maybe even use a metric such as average hamming distance between the individuals to compare the difference.

**Comment by Regan-Koopmans** [comment]
I added code to the end to the Individual constructor to  increase diversity before the demo, namely:

```python
for i in range(1, length+1):
    if bool(random.getrandbits(1)):
        self.flip(i)
```

This enhances the diversity, but not intelligently through any measurements. Do you feel that this is sufficient?
