### ISSUE TITLE
Export graph to image and CSV

### ISSUE THREAD

**Issue by Regan-Koopmans** [ErnstEksteen/COS301_GA-SATSolver#60]

**Comment by DewaldDeJager** [comment]
Exporting the data necessary to reproduce the plot (x and y value of each dot of each line plot) in CSV format could also be a nice feature.

**Comment by Regan-Koopmans** [comment]
I have added the option to export to CSV, but it only writes the fitness values to the file. This means that although the concept of a generation is captured implicitly with each value, we do not know what the first generation was (since the interface can start observing at any point.

One alternative is two have the CVS in the format `<fitness>, <generation>, <fitness> ...`. This would explicitly show the generation count.

Another alternative is to  have the first generation count. That is, of the format `<first-generation-count>, <fitness>, <fitness>, <fitness> ...`. The rest of the x axis can be generated/inferred from this information.

I believe we should vote on what format would be the most ideal, balancing human-readability with efficiency.

**Comment by DewaldDeJager** [comment]
I think a good format for the CSV file is:

```
Generation, Fitness Value of Best Individual, Fitness Value of Newest Child
<generation>,<fitness>,<fitness>
<generation>,<fitness>,<fitness>
...
<generation>,<fitness>,<fitness>
```

This is purely because it is a flat file and the redundancy is what makes it easy to work with. Typically CSV files also have a header and each row is a record, so that would make it clear what everything means just from looking at the CSV.
